eureka:
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-peer2:8761/eureka/
  instance:
    hostname: eureka-peer1
    appname: eureka-cluster
server:
  port: 8762