eureka:
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-peer1:8762/eureka/
  instance:
    hostname: eureka-peer2
    appname: eureka-cluster
server:
  port: 8761